### ISSUE TITLE
npm?

### ISSUE THREAD

**Issue by azu** [soyjavi/hamsa#1]
Hi, thanks for nice library!

Could this be packaged as an npm module?

```
npm install hamsa
```

**Comment by soyjavi** [comment]
Tomorrow I will create a NPM ... Thanks

—
Javi Jiménez Villar
@soyjavi

**Comment by soyjavi** [comment]
Fixed! New version 0.3.23 http://gethamsa.com/#install

**Comment by azu** [comment]
Thanks!
