### ISSUE TITLE
Example not working

### ISSUE THREAD

**Issue by beyondgrayzone** [soyjavi/hamsa#2]
I tried to copy paste your example javascript form the website, but it keeps throwing error "undefined" on 

___extends(Contact, _super);_ and    return Contact. __ super __ .constructor.apply(this, arguments);

I replaced __extends with jQuery.extend and it works but other error still pops up.

It would be great if you could guide how can I use this library. 

Thanks

**Comment by soyjavi** [comment]
You're right... I need provide __extend method (is a coffeescript method) inside hamsa.js. Today I'll fix it :)

**Comment by soyjavi** [comment]
Hi! I just fixed the error. https://github.com/soyjavi/hamsa/commit/c841aa9ab8abcdfdece83f1adf0d256c4bcb9c8c

You need use `_extends` method in the global space:

```
var Contact = (function(_super) {
  _extends(Contact, _super);

  function Contact() {
    return Contact.__super__.constructor.apply(this, arguments);
  }

  Contact.define({
    id        : { type: String },
    mail      : { type: String },
    username  : { type: String },
    avatar    : { type: String, default: "http://gravatar.org" },
    networks  : { type: Object },
    since     : { type: Number, default: 2015 },
    created_at: { type: Date, default: new Date() }
  });

  return Contact;

})(Hamsa);
```

**Comment by beyondgrayzone** [comment]
Thank you. Its working!

**Comment by beyondgrayzone** [comment]
Although its working and I can see the entire object in console,  I cannot access the object properties (example obj.username).
![bug](https://cloud.githubusercontent.com/assets/7389244/6804208/d3919de6-d212-11e4-89a6-5186d5821283.png)

This is the JS code

```
var obj ;

var Contact = (function(_super) {
  _extends(Contact, _super);

  function Contact() {
    return Contact.__super__.constructor.apply(this, arguments);
  }

  Contact.define({
    id        : { type: String },
    mail      : { type: String },
    username  : { type: String },
    avatar    : { type: String, default: "http://gravatar.org" },
    networks  : { type: Object },
    since     : { type: Number, default: 2015 },
    created_at: { type: Date, default: new Date() }
  });

  return Contact;

})(Hamsa);

var MUTATIONS = ["add", "update"];

var callback = function(state) {
  obj = state.object ;
  return console.log(obj);
};

Contact.observe(callback, MUTATIONS);

jd = new Contact({username: "JonDoe", mail: "someid@web.tld"});
```

**Comment by soyjavi** [comment]
Ok, I'll check ... today I will upgrade a new version with a casting for all values.

**Comment by soyjavi** [comment]
Ok, I understand your problem and I fix it -> https://github.com/soyjavi/hamsa/commit/7de744feba39feccb66131a4d695032a7ba80a73 now there is a new release (bower && npm) 0.3.25

**Comment by beyondgrayzone** [comment]
Sorry if I confused you. In my previous comment, I slightly modified your example code inside **callback** function. I saved the **state** argument in **obj** variable, so I could see it in chrome console. 

But if I were to keep everything simple, your example javascript code for callback is printing **state.object.username**, but it says **undefined** ! Then I opened up console and ran the modifed code shown above and I see that it has some unique ID associated with the object and now you can access the proprties like this shown below and it successfully returns the value.

![bugg](https://cloud.githubusercontent.com/assets/7389244/6825316/1b2d4c96-d2d0-11e4-919b-09a15482210f.jpg)

But you cannot access the same properties directly like this **obj.username** or **state.object.username**.

**Comment by soyjavi** [comment]
Have you tried to update the new version?

**Comment by beyondgrayzone** [comment]
Thanks a lot for the help. It now works as expected!
