### ISSUE TITLE
What should be the correct behavior for mutation observer?

### ISSUE THREAD

**Issue by beyondgrayzone** [soyjavi/hamsa#3]
Take this code for example

```
var MUTATIONS = ["add", "update", "delete"];// each event should pass the right object to the callback

var callback = function(state) {
  obj = state.object ;
  return console.log("User Name : --> " + obj.username);
};

Contact.observe(callback, MUTATIONS);

jd = new Contact({username: "JonDoe"}, callback, MUTATIONS );
jd.username = "JaneDoe";
delete jd.username;
```

In the above code, see the last three lines. First create(add), then update and at the end delete. If you run this code, console.log prints "undefined" 3 times each for every mutation. In other words the callback gets the object that got mutated the last (in this case delete). In my opinion this behavior is a little bit weird. **add**  mutation should call the callback with the object created with **new** and **update** should pass entirely new instance to the callback. Same goes with the **delete**.

So the output should looks like this instead.
1. User Name : --> JonDoe
2. User Name : --> JaneDoe
3. User Name : --> undefined

P.S. This is just my opinion.

**Comment by soyjavi** [comment]
Hi,

Object.Observe collect mutations in a determinate period of time... in a real case you never do that (add, update and destroy in the same time). Please try this:

```
var jd = new Contact({username: "JonDoe"}, callback, MUTATIONS);
setTimeout(function() { jd.username = "JaneDoe";}, 100);
setTimeout(function() { delete jd.username; }, 200);
```

I need respect the "standard" :)

**Comment by beyondgrayzone** [comment]
Oh, I didn't know Object.Observe has an internal scheduler. This makes total sense now. Thanks.
