### ISSUE TITLE
Small changes to home?

### ISSUE THREAD

**Issue by slowdownitsfine** [soyjavi/hamsa#4]
Hola SoyJavi,

tiene buena pinta Hamsa, pero leyendo la descripción en [gethamsa.com](http://gethamsa.com/) he visto algunos errores menores en el inglés. Me aceptarías una PR con algunos cambios?

**Comment by soyjavi** [comment]
claro que si tio!!! soy muy malo with the copyleft

—
Javi Jiménez Villar
@soyjavi
